// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxclnugmkrjcgbbubzpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4Y2xudWdta3JqY2diYnVienB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzE4NTksImV4cCI6MjA3MTk0Nzg1OX0.nY7qj2PW-hRvdoRWS1wvBrJXtSpIg8TNHsmJySwlwaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});